export const googleFontPairingMenus = [
  { title: null, content: null },
  { title: "font-merriweather", content: "font-openSans" },
  { title: "font-playfairDisplay", content: "font-montserrat" },
  { title: "font-lora", content: "font-lato" },
  { title: "font-roboto", content: "font-robotoSlab" },
  { title: "font-PTSerif", content: "font-PTSans" },
  { title: "font-oswald", content: "font-raleway" },
  { title: "font-bitter", content: "font-sourceSans3" },
  { title: "font-nunito", content: "font-nunitoSans" },
  { title: "font-ubuntu", content: "font-lora" },
  { title: "font-spectral", content: "font-rubik" },
  { title: "font-oswald", content: "font-notoSans" },
  { title: "font-spaceMono", content: "font-muli" },
  { title: "font-fjalaOne", content: "font-libreBaskerville" },
  { title: "font-cinzel", content: "font-faunaOne" },
  { title: "font-abrilFatface", content: "font-poppins" },
  { title: "font-ubuntu", content: "font-lora" },
];

export const googleFontList = [
  { title: "Bebas Neue", classTw: "font-bebasNeue", type: "sans-serif" },
  { title: "Poppins", classTw: "font-poppins", type: "sans-serif" },
  { title: "Merriweather", classTw: "font-merriweather", type: "serif" },
  { title: "Open Sans", classTw: "font-openSans", type: "sans-serif" },
  { title: "Nunito Sans", classTw: "font-nunitoSans", type: "sans-serif" },
  { title: "Nunito", classTw: "font-nunito", type: "sans-serif" },
  { title: "Source Sans 3", classTw: "font-sourceSans3", type: "sans-serif" },
  { title: "Bitter", classTw: "font-bitter", type: "serif" },
  { title: "Raleway", classTw: "font-raleway", type: "sans-serif" },
  { title: "Oswald", classTw: "font-oswald", type: "sans-serif" },
  { title: "PT Sans", classTw: "font-PTSans", type: "sans-serif" },
  { title: "PT Serif", classTw: "font-PTSerif", type: "serif" },
  { title: "Roboto Slab", classTw: "font-robotoSlab", type: "serif" },
  { title: "Roboto", classTw: "font-roboto", type: "sans-serif" },
  { title: "Loto", classTw: "font-loto", type: "sans-serif" },
  { title: "Lora", classTw: "font-lora", type: "serif" },
  { title: "Montserrat", classTw: "font-montserrat", type: "sans-serif" },
  { title: "Playfair Display", classTw: "font-playfairDisplay", type: "serif" },
  { title: "Ubuntu", classTw: "font-ubuntu", type: "sans-serif" },
  { title: "Abril Fatface", classTw: "font-abrilFatface", type: "serif" },
  { title: "Fauna One", classTw: "font-faunaOne", type: "serif" },
  { title: "Cinzel", classTw: "font-cinzel", type: "serif" },
  { title: "Libre Baskerville", classTw: "font-libreBaskerville", type: "serif" },
  { title: "Fjalla One", classTw: "font-fjallaOne", type: "sans-serif" },
  { title: "Mulish", classTw: "font-mulish", type: "sans-serif" },
  { title: "Space Mono", classTw: "font-spaceMono", type: "monospace" },
  { title: "Noto Sans", classTw: "font-notoSans", type: "sans-serif" },
  { title: "Rubik", classTw: "font-rubik", type: "sans-serif" },
  { title: "Spectral", classTw: "font-spectral", type: "serif" },
];
