export const popularWeb = [
  {
    type: "E-commerce Website",
    features: ["Product listings", "Shopping cart", "Secure checkout"],
    navbarMenu: ["Home", "Shop", "About Us", "Contact"],
    heroContent: "Large product image with a call-to-action",
    exampleWebsite: "Amazon.com",
    description: "Online platform for buying and selling goods",
    colorPreference: {
      primary: "#FF9900",
      secondary: "#232F3E",
      accent: "#FFCC00",
    },
  },
  {
    type: "Social Media Platform",
    features: ["User profiles", "News feeds", "Messaging"],
    navbarMenu: ["Home", "Profile", "Messages", "Notifications"],
    heroContent: "Latest posts or trending topics",
    exampleWebsite: "Facebook.com",
    description: "Connects people online through shared interests and activities",
    colorPreference: {
      primary: "#3B5998",
      secondary: "#FFFFFF",
      accent: "#FF0000",
    },
  },
  {
    type: "News Website",
    features: ["Articles", "Categories", "Search functionality"],
    navbarMenu: ["Home", "News", "Opinion", "Sports", "Business"],
    heroContent: "Breaking news headline and image",
    exampleWebsite: "CNN.com",
    description: "Provides current events and information",
    colorPreference: {
      primary: "#CC0000",
      secondary: "#000000",
      accent: "#FFCC00",
    },
  },
  {
    type: "Blog",
    features: ["Articles", "Categories/Tags", "Comments section"],
    navbarMenu: ["Home", "Blog", "About", "Contact"],
    heroContent: "Featured blog post with an excerpt",
    exampleWebsite: "Medium.com",
    description: "Personal or professional articles and insights",
    colorPreference: {
      primary: "#02B875",
      secondary: "#FFFFFF",
      accent: "#FF9900",
    },
  },
  {
    type: "Portfolio Website",
    features: ["Projects", "Client testimonials", "Contact form"],
    navbarMenu: ["Home", "Portfolio", "About", "Contact"],
    heroContent: "Showcase of best work/projects",
    exampleWebsite: "Behance.net",
    description: "Displays creative work to attract clients or employers",
    colorPreference: {
      primary: "#1769FF",
      secondary: "#1F2937",
      accent: "#FFCA3A",
    },
  },
  {
    type: "Educational Website",
    features: ["Courses", "Resources", "Student login"],
    navbarMenu: ["Home", "Courses", "About Us", "Contact"],
    heroContent: "Featured course or educational content",
    exampleWebsite: "Coursera.org",
    description: "Offers learning materials and courses online",
    colorPreference: {
      primary: "#2A73CC",
      secondary: "#F6F8FA",
      accent: "#FFAB00",
    },
  },
  {
    type: "Corporate Website",
    features: ["Company information", "Careers", "Investor relations"],
    navbarMenu: ["Home", "About Us", "Products/Services", "Careers"],
    heroContent: "Brand message or product/service highlight",
    exampleWebsite: "Apple.com",
    description: "Represents a company and its offerings",
    colorPreference: {
      primary: "#333333",
      secondary: "#FFFFFF",
      accent: "#B6B6B6",
    },
  },
  {
    type: "Portfolio Website (Photography)",
    features: ["Photo galleries", "Services offered", "Contact form"],
    navbarMenu: ["Home", "Portfolio", "Services", "Contact"],
    heroContent: "Stunning photography showcase",
    exampleWebsite: "NationalGeographic.com",
    description: "Showcases professional photography work",
    colorPreference: {
      primary: "#FFD700",
      secondary: "#000000",
      accent: "#008080",
    },
  },
  {
    type: "Travel Website",
    features: ["Destinations", "Booking options", "Travel guides"],
    navbarMenu: ["Home", "Destinations", "Deals", "Contact"],
    heroContent: "Beautiful travel destination image",
    exampleWebsite: "Booking.com",
    description: "Helps users plan and book travel accommodations",
    colorPreference: {
      primary: "#003580",
      secondary: "#FFFFFF",
      accent: "#00A698",
    },
  },
  {
    type: "Healthcare Website",
    features: ["Services", "Patient resources", "Appointment booking"],
    navbarMenu: ["Home", "Services", "About Us", "Contact"],
    heroContent: "Health tips or service highlights",
    exampleWebsite: "WebMD.com",
    description: "Provides health-related information and services",
    colorPreference: {
      primary: "#0073E6",
      secondary: "#FFFFFF",
      accent: "#00CC99",
    },
  },
  {
    type: "Real Estate Website",
    features: ["Property listings", "Mortgage calculator", "Agent profiles"],
    navbarMenu: ["Home", "Properties", "About Us", "Contact"],
    heroContent: "Featured property listing",
    exampleWebsite: "Zillow.com",
    description: "Helps users buy, sell, or rent properties",
    colorPreference: {
      primary: "#006AFF",
      secondary: "#FFFFFF",
      accent: "#FFB81C",
    },
  },
  {
    type: "Job Board",
    features: ["Job listings", "Resume upload", "Employer profiles"],
    navbarMenu: ["Home", "Jobs", "Employers", "About Us"],
    heroContent: "Featured job openings",
    exampleWebsite: "Indeed.com",
    description: "Connects job seekers with employers",
    colorPreference: {
      primary: "#2164F4",
      secondary: "#FFFFFF",
      accent: "#FF9900",
    },
  },
  {
    type: "Dating Website",
    features: ["Profiles", "Messaging", "Matchmaking algorithms"],
    navbarMenu: ["Home", "Profiles", "Messages", "Settings"],
    heroContent: "Featured user profiles or success stories",
    exampleWebsite: "Match.com",
    description: "Connects individuals seeking romantic relationships",
    colorPreference: {
      primary: "#FF0040",
      secondary: "#FFFFFF",
      accent: "#FFD700",
    },
  },
  {
    type: "Government Website",
    features: ["Services", "Regulations", "News updates"],
    navbarMenu: ["Home", "Services", "News", "Contact Us"],
    heroContent: "Government initiatives or news",
    exampleWebsite: "USA.gov",
    description: "Provides information and services from governmental agencies",
    colorPreference: {
      primary: "#FF0000",
      secondary: "#FFFFFF",
      accent: "#000000",
    },
  },
  {
    type: "Nonprofit Organization Website",
    features: ["Mission statement", "Donation options", "Volunteer opportunities"],
    navbarMenu: ["Home", "About Us", "Donate", "Contact"],
    heroContent: "Impact stories or urgent campaigns",
    exampleWebsite: "RedCross.org",
    description: "Raises awareness and funds for charitable causes",
    colorPreference: {
      primary: "#CC0000",
      secondary: "#FFFFFF",
      accent: "#0033A0",
    },
  },
  {
    type: "Video Streaming Platform",
    features: ["Video content", "Playlists", "User subscriptions"],
    navbarMenu: ["Home", "Videos", "Channels", "Sign In"],
    heroContent: "Featured videos or trending content",
    exampleWebsite: "YouTube.com",
    description: "Allows users to watch and share videos online",
    colorPreference: {
      primary: "#FF0000",
      secondary: "#FFFFFF",
      accent: "#FFD700",
    },
  },
  {
    type: "Forum",
    features: ["Discussion threads", "User profiles", "Moderators"],
    navbarMenu: ["Home", "Forums", "Members", "Search"],
    heroContent: "Featured discussion topic",
    exampleWebsite: "Reddit.com",
    description: "Facilitates online discussions on various topics",
    colorPreference: {
      primary: "#FF5700",
      secondary: "#FFFFFF",
      accent: "#336699",
    },
  },
  {
    type: "Gaming Website",
    features: ["Games", "Leaderboards", "Community forums"],
    navbarMenu: ["Home", "Games", "Forums", "Support"],
    heroContent: "Featured game or gaming news",
    exampleWebsite: "SteamCommunity.com",
    description: "Connects gamers and",
  },
];
